version: "3.9"
services:
  surepet-metrics:
    build: .
    image: jonootto/surepet-metrics:latest
    container_name: surepet-metrics
    restart: unless-stopped
    environment: 
        SUREPY_TOKEN: $SUREPY_TOKEN
        INFLUX_TOKEN: $INFLUX_TOKEN
        ORG: $ORG
        BUCKET: $BUCKET
        HOST_URL: $HOST_URL
    #security_opt:
    #  - seccomp:unconfined
